# Setup
title:               My awesome blogik
tagline:             'A Jekyll theme'
description:         'For random thoughts.'
url:                 https://barsv.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Stanislav Baranov
  email:             barsv85@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
