# Setup
title:               My awesome blogik
tagline:             'Naher tagline'
description:         'For random thoughts.'
url:                 https://barsv.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
github:
  repo: https://github.com/barsv/barsv.github.io

# About/contact
author:
  name:              Stanislav Baranov
  email:             barsv85@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
